apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:latest
        name: web-app
        ports:
        - containerPort: 8080
      - image: mysql:8.0
        name: sql-db
        ports:
        - containerPort: 3306
